services:
  db:
    image: postgres:17-alpine
    container_name: doga_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: minio/minio
    container_name: doga_s3
    ports:
      - "9000:9000" # API用
      - "9001:9001" # 管理画面（コンソール）用
    environment:
      MINIO_ROOT_USER: ${S3_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${S3_ROOT_PASSWORD} # 8文字以上
    volumes:
      - minio_data:/data # 動画データの保存先
    command: server /data --console-address ":9001"

#   backend:
#     build: ./backend
#     container_name: doga_api
#     ports:
#       - "8000:8000"
#     environment:
#       DATABASE_URL: postgresql://user:password@db:5432/doga
#     depends_on:
#       - db

#   frontend:
#     build: ./frontend
#     container_name: doga_web
#     ports:
#       - "3000:3000"
#     environment:
#       PUBLIC_API_URL: http://localhost:8000
#     depends_on:
#       - backend

volumes:
  postgres_data:
  minio_data: